---
output: pdf_document
always_allow_html: yes
---

```{r setup, echo=FALSE,results="hide", include=FALSE}

options(stringsAsFactors = FALSE)

# Smart require checks to see if the libraries are present, installs them if
# necessary, and loads them:

smartRequire <- function(packages){
  # Get vector of packages listed that aren't on the current computer
  packagesToInstall <- packages[!packages %in% rownames(installed.packages())]
  if(length(packagesToInstall > 0)){
    install.packages(packagesToInstall, dependencies = TRUE)
  }
  lapply(packages, require, character.only = TRUE)
}

smartRequire(c('tidyverse', 'lubridate','stringr',
               'knitr', 'rmarkdown', 'mongolite', 'DT'))

```


```{r functions, echo=FALSE,results="hide", include=FALSE}
# Function to query mongo database table by hub:

getSitesMongo <- function(hubField, inHub){
  hubQueryStatement <- str_c('{',
                             shQuote(hubField, type = 'cmd'),
                             ':',
                             shQuote(inHub, type = 'cmd'),
                             '}')
  siteVector <- siteIdMongo$find(
    query = hubQueryStatement,
    fields = '{"_row" : 0, "_id" : 0}'
  ) %>%
    mongoToTblDf %>%
    .$siteID %>%
    unique
  return(siteVector)
}

# Query captures for a given hub:

getCapturesHubMongo <- function(hubField, inHub){
  inSites <- getSites(hubField, inHub)
  siteQueryStatement <- paste0('{', 
                               shQuote('siteIDCapture', type = 'cmd'),
                               ' : {"$in" : [',
                               paste(shQuote(inSites, type = 'cmd'),
                                     collapse = ' , '),
                               '] }}')
  captureSubset <- captureMongo$find(
    query = siteQueryStatement,
    fields = '{"_row" : 0, "_id" : 0}'
  ) %>%
    mongoToTblDf
  return(captureSubset)
}

getSppColor <- function(capturesHub){
  if(nrow(capturesHub) > 0){
    return(
      capturesHub %>%
        select(sppCapture, colorComboCapture) %>%
        distinct
    )  
  } else {
    return(NULL)
  }
}

# Function to replace color combo with named colors:

replaceColorCode <- function(fromColorCombo){
  fromColorCombo %>% 
    str_split_fixed(',', 2) %>% 
    as.data.frame %>%
    setNames(c('left', 'right')) %>%
    mutate(
      left = gsub('^([A-Z]{1})([A-Z])$', '\\1/\\2', left),
      right = gsub('^([A-Z]{1})([A-Z])$', '\\1/\\2', right),
      left = ifelse(left == '', '-', left) %>%
        str_replace_all(colorNamedVector) %>%
        str_to_title,
      right = ifelse(right == '', '-', right) %>%
        str_replace_all(colorNamedVector) %>%
        str_to_title
    ) 
}

# Function to get color combinations:

getColorCombos <- function(colorVector, nBands, 
                           xPositions = 1:4, aluminum = TRUE){
  if(aluminum == TRUE) colorVector <- c(colorVector, 'X')
  if(nBands!= 4) colorVector <- c(colorVector, '-')
  colorList <- rep(list(colorVector), 4)
  colorGrid <- expand.grid(colorList, stringsAsFactors = FALSE) %>%
    unite(col = combinedCol, 1:4, sep = '') %>%
    filter(str_count(combinedCol, '-') == 4 - nBands)
  if(aluminum == TRUE){
    colorGrid <- colorGrid %>%
      filter(str_count(combinedCol, 'X') == 1,
             str_locate(combinedCol, 'X')[,1] %in% xPositions)
  }
  colorCombos <- colorGrid %>%
    separate(col = combinedCol, into = c('colorL', 'colorR'), sep = 2) %>%
    mutate_all(str_replace_all, pattern = '-', replacement = '')
  return(
    sample_n(colorCombos, nrow(colorCombos)) %>%
      distinct
  )
}

# Function to get used color combos for a given Nestwatch hub and species:

getUsedNestwatchCombos <- function(capturesHub, species){
  sppColorFrame <- getSppColor(capturesHub)
  if(species %in% c('BCCH', 'CACH', 'UNCH')){
    species <- c('BCCH', 'CACH', 'UNCH')
  }
  if(is.null(sppColorFrame)){
    return(NULL)
  } else {
    if(nrow(sppColorFrame > 0)){
      colorFrame <- sppColorFrame %>%
        filter(sppCapture == species)
      if(nrow(colorFrame) > 0){
        return(
          colorFrame$colorComboCapture %>%
            unique
        )
      } else {
        return(NULL)
      }
    } else {
      return(NULL)
    }
  }
}

# Function to get used color combos for nzpBanding:

getUsedNZPCombos <- function(nzpBanding, SPP){
  sppColorFrame <- nzpBanding %>%
    transmute(
      spp = SPP,
      colorCombo = paste(colorComboL, colorComboR, sep = ',')
    ) %>%
    filter(spp == species)
  if(nrow(sppColorFrame) > 0){
    return(
      sppColorFrame$colorCombo %>%
        unique
    )
  } else {
    return(NULL)
  }
}

# Function to get used color combos across nzpBanding and Nestwatch:

getUsedCombos <- function(nzpBanding, nnBanding, species){
  # Used combos, NZP:
  usedCombosNZP <- getUsedNZPCombos(nzpBanding, species)
  # Nestwatch species to watch out for
  nnSppVector <- c('AMRO','CACH','CARW','GRCA',
                          'HOWR','NOCA','NOMO','SOSP')
  if(!species %in% nnSppVector){
    usedCombos <- usedCombosNZP
  } else {
    usedCombos <- c(
      usedCombosNZP,
      getUsedNestwatchCombos(nnBanding, species)
    )
  }
  return(usedCombos)
}

# Function to make data frame of unused color combos:

getUnusedColors <- function(nzpBanding, nnBanding, species, nColors,
                            colorVector, 
                            xPositions = 1:4, aluminum = TRUE,
                            onlyWithColor = FALSE, specifiedColor = 'P',
                            removeColor = 'N'){
  # Get data frame of potential colors
  potentialColors <- getColorCombos(colorVector, nColors, xPositions, aluminum) %>%
    tbl_df %>%
    transmute(colorCombo = paste(colorL, colorR, sep = ','))
  potentialColorsFull <- bind_cols(
    potentialColors,
    replaceColorCode(potentialColors$colorCombo)
  )
  # Get vector of used colors for a Nestwatch hub:
  usedCombos <- getUsedCombos(nzpBanding, nnBanding, species)
  # Subset data frame to unused combos:
  if(!is.null(usedCombos)){
    comboSubset <- potentialColorsFull %>%
      filter(!colorCombo %in% usedCombos)
  } else {
    comboSubset <- potentialColorsFull
  }
  if(onlyWithColor == TRUE){
    comboSubset <- comboSubset %>%
      filter(str_detect(colorCombo, specifiedColor))
  }
  if(removeColor != 'N'){
    comboSubset <- comboSubset %>%
      filter(!str_detect(colorCombo, removeColor))
  }
  return(comboSubset)
}

# Function to make a data table:

dataTableFun <- function(inTable){
  datatable(inTable, 
                rownames = FALSE,
                class = 'cell-border stripe',
                options = list(
                  pageLength = 25,
                  dom = 't',
                  ordering = FALSE,
                  autoWidth = TRUE,
                  columnsDefs = list(
                    list(className = 'dt-center', targets = c(0:2))
                  )
                )
  ) %>%
    formatStyle(1:7, fontSize = '12px') %>%
    formatStyle(1:3, textAlign = 'center')
}

```

```{r inputs, echo=FALSE,results="hide", include=FALSE}
# # Where's mongo?
# 
# mongoURL <- "mongodb://bsevans:33shazam@ds025232.mlab.com:25232/nndataentry"
# 
# # Load necessary mongo connections:
# 
# siteIdMongo <- mongo('siteIdTable', url = mongoURL)
# captureMongo <- mongo('captureTable', url = mongoURL)

# Set hub field:

hubField <- 'region'

# Get NZP banding file:

nzpBanding <- read_csv('nzpBanding_2017-08-25.csv') %>%
  filter(!is.na(spp))

# Get NN banding file

nnBanding <- read_csv('captureTable_2017-08-15.csv') %>%
  filter(!is.na(sppCapture))

# Get vector of colors:

colorVector <- c('K', 'B', 'G','M', 'O','P', 'R','W', 'Y')

# Color conversion frame:

colorFrame <- data.frame(
  colorCode = c('-','X', colorVector),
  color = c('-','alum', 'black', 'blue', 'green', 'purple',
            'orange','pink', 'red', 'white', 'yellow')
)

# Color named vector:

colorNamedVector <- colorFrame$color
names(colorNamedVector) <- colorFrame$colorCode

# Number of bands?

nColors <- 3

# At which position(s) should the aluminum be?

xPosition <- 2

# What species are you making sheets for? 

species <- c('AMGO', 'AMRO', 'CACH', 'CARW','DEJU','EUST',
            'GRCA','HOFI','HOSP','HOWR','NOCA','NOMO',
            'SOSP','TUTI','WBNU','WTSP')

# Conditions frame:

conditionsFrame <- data_frame(
  # What species are you making sheets for? 
  species = species
) %>%
  mutate(
    # Vector of aluminum band true and falses:
    al = ifelse(species %in% c('EUST', 'HOSP'),  FALSE, TRUE),
    nBands = ifelse(species %in% c('EUST', 'HOSP'),  3, 4),
    removeColor = ifelse(
      species %in% c('AMGO', 'CACH', 'DEJU','HOWR'), 'M', 'N'
    )
  )
```

```{r tableGeneration, echo=FALSE,results="hide", include=FALSE}

# Conditions:

SPP <- conditionsFrame$species[i]
al <- conditionsFrame$al[i]
nBands  <- conditionsFrame$nBands[i]
colorToRemove  <- conditionsFrame$removeColor[i]

# Color table:
  
colorTable <- getUnusedColors(nzpBanding, nnBanding, SPP, nColors = nBands,
                            colorVector, 
                            xPositions = 2, aluminum = al,
                            onlyWithColor = FALSE,
                            removeColor = colorToRemove) %>%
  rename(combo = colorCombo) %>%
  mutate(date = '',
         bandNumber = '           ',
         sex = '') %>%
  data.frame %>%
  slice(1:22)
```

```{r printTable, echo=FALSE, message=FALSE, results= 'asis'}
out <- NULL
j <- 1
knit_expandedHeader <- paste0("`r \n\nSPP`\n")
knit_expanded <- paste0("\n```{r results='asis', echo=FALSE}\n\ndataTableFun(colorTable)\n\n```")
out <- c(out, knit_expandedHeader,knit_expanded)
```

`r paste(knit(text = out), collapse = '\n')`

